### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Vinz87** [osh/gr-eventstream#21]
I'm trying to compile it on OS X El Capitan, but I get this error when I do cmake:

`[ 87%] Linking CXX shared module _es_swig.so
Undefined symbols for architecture x86_64:
  "log4cpp::CategoryStream::~CategoryStream()", referenced from:
      gr::logger::debug(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::info(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::notice(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::warn(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::crit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::alert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      ...
  "log4cpp::CategoryStream::operator<<(log4cpp::CategoryStream& (*)(log4cpp::CategoryStream&))", referenced from:
      gr::logger::debug(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::info(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::notice(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::warn(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::crit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::alert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      ...
  "log4cpp::eol(log4cpp::CategoryStream&)", referenced from:
      gr::logger::debug(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::info(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::notice(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::warn(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::crit(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      gr::logger::alert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in es_swigPYTHON_wrap.cxx.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [swig/_es_swig.so] Error 1
make[1]: *** [swig/CMakeFiles/_es_swig.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by osh** [comment]
this appears to be a gr:logger or log4cpp issue, I've not actually tested on OS X as I do not own any OS X machines.  If you have a patch to resolve the issue I would be happy to merge it -

**Comment by osh** [comment]
closing because this issue is not gr-eventstream's fault
