### ISSUE TITLE
CentOS 6.4 6.5 6.6 failed to build from source 

### ISSUE THREAD

**Issue by sgardner340** [osh/gr-eventstream#9]
Error I received:

Current step: (gr-eventstream :: make)
make
bashexec (/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/src/gr-eventstream/build)::
find . -name '*.make' -print0 | xargs -0 sed -i 's/\(^.*\)\(--cyan \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--green \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--red --bold \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--blue --bold \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/'
find . -name 'Makefile' -print0 | xargs -0 sed -i 's/\(^.*\)\(--cyan \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--green \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--red --bold \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/;s/\(^.*\)\(--blue --bold \"\)\(.*\)\"$/\1\2\x1b\3\x1b\"/'
ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/cc
ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/gcc
ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/c++
ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/colorgcc.pl /apps/smokey64/bin/g++
make -j4
Scanning dependencies of target pygen_swig_45437
[ 2%] Scanning dependencies of target pygen_python_58d50
Generating __init__.pyc
[ 5%] Scanning dependencies of target es_swig_swig_2d0df
[ 8%] Generating es_trigger_keyboard.pyc, es_trigger_timer.pyc, util.pyc
Generating __init__.pyo
[ 10%] [ 10%] Built target pygen_swig_45437
Building CXX object swig/CMakeFiles/es_swig_swig_2d0df.dir/es_swig_swig_2d0df.cpp.o
[ 13%] Generating es_trigger_keyboard.pyo, es_trigger_timer.pyo, util.pyo
[ 13%] Built target pygen_python_58d50
Linking CXX executable es_swig_swig_2d0df
Swig source
Scanning dependencies of target eventstream
[ 16%] [ 18%] Building CXX object lib/CMakeFiles/eventstream.dir/es_eh_pair.cc.o
Building CXX object lib/CMakeFiles/eventstream.dir/es_common.cc.o
[ 21%] Building CXX object lib/CMakeFiles/eventstream.dir/es_event_loop_thread.cc.o
[ 24%] Building CXX object lib/CMakeFiles/eventstream.dir/es_source_thread.cc.o
[ 27%] Building CXX object lib/CMakeFiles/eventstream.dir/es_handler.cc.o
[ 29%] Building CXX object lib/CMakeFiles/eventstream.dir/es_handler_flowgraph.cc.o
[ 32%] Building CXX object lib/CMakeFiles/eventstream.dir/es_handler_print.cc.o
[ 32%] Built target es_swig_swig_2d0df
[ 35%] Building CXX object lib/CMakeFiles/eventstream.dir/es_handler_file.cc.o
[ 37%] Building CXX object lib/CMakeFiles/eventstream.dir/es_handler_pdu.cc.o
[ 40%] Building CXX object lib/CMakeFiles/eventstream.dir/es_queue.cc.o
Scanning dependencies of target pygen_swig_52287
[ 43%] Generating es_swig.pyc
[ 45%] Generating es_swig.pyo
[ 45%] Built target pygen_swig_52287
[ 48%] Building CXX object lib/CMakeFiles/eventstream.dir/es_sink.cc.o
/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/src/gr-eventstream/lib/es_queue.cc: In member function ‘ size_t es_queue::find_binary(uint64_t) ’:
/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/src/gr-eventstream/lib/es_queue.cc: 119: error: using ‘ typename ’ outside of template
make[2]: *** [lib/CMakeFiles/eventstream.dir/es_queue.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/CMakeFiles/eventstream.dir/all] Error 2
make: *** [all] Error 2
bash return val = 2
Traceback (most recent call last):
File "./pybombs", line 360, in
main()
File "./pybombs", line 357, in main
sys.exit(cli(parser,opts,args))
File "./pybombs", line 171, in cli
pybombs_ops.install(p, not opts.force);
File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/pybombs_ops.py", line 151, in install
global_recipes[pkg].install();
File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 531, in install
st = self.install_src();
File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 598, in install_src
self.install_order[step][1]();
File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.4_Desktop_x86_VM_R/satisfy_order/src-rpm/mod_pybombs/recipe.py", line 658, in make
assert(st == 0);
AssertionError
Build step 'Execute shell' marked build as failure
[WARNINGS] Skipping publisher since build result is FAILURE
Email was triggered for: 1st Failure
Trigger Failure was overridden by another trigger and will not send an email.
Trigger Still Failing was overridden by another trigger and will not send an email.
Sending email for trigger: 1st Failure

**Comment by osh** [comment]
hrm...
gr-eventstream/lib/es_queue.cc: 119: error: using ‘ typename ’ outside of template
will have to look into this

**Comment by sgardner340** [comment]
Okay thanks


On Fri, Aug 28, 2015 at 12:30 PM, osh <notifications@github.com> wrote:

> hrm...
> gr-eventstream/lib/es_queue.cc: 119: error: using ‘ typename ’ outside of
> template
> will have to look into this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osh/gr-eventstream/issues/9#issuecomment-135825884>.
>



-- 
Steven Gardner
All good men know the power of prayer...

**Comment by osh** [comment]
can't seem to reproduce the error with gcc 4.8.4
what version of gcc are you using?

**Comment by sgardner340** [comment]
CentOS 6.4: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
CentOS 6.5: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
CentOS 6.6: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

On Fri, Aug 28, 2015 at 1:17 PM, osh <notifications@github.com> wrote:

> can't seem to reproduce the error with gcc 4.8.4
> what version of gcc are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osh/gr-eventstream/issues/9#issuecomment-135836717>.
>



-- 
Steven Gardner
All good men know the power of prayer...

**Comment by gr-sp** [comment]
Please see http://www.cmake.org/Bug/view.php?id=14441

This looks like something picked up my later versions of cmake. It should only be generating a warning. On my Ubuntu 14 machine with cmake 2.8.12.2 but gr-eventstream still builds just fine. It looks like a possible issue with syntax in GrPython.cmake. It looks like the version of GrPython.cmake in GNU Radio has fixed this issue. Maybe we should just copy that version over to the gr-eventstream project?

**Comment by gr-sp** [comment]
If its any help, I have built this under both gcc 4.8.4 and gcc 4.6.3.

**Comment by gr-sp** [comment]
I have a fix coming.

**Comment by sgardner340** [comment]
Hi Tim

Thanks for your help, I will resume working on this as some as my network
team gets the ("more-reliable") new system that host my virtual machines up
and running again.....

On Mon, Aug 31, 2015 at 10:02 AM, gr-sp <notifications@github.com> wrote:

> I have a fix coming.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osh/gr-eventstream/issues/9#issuecomment-136379803>.
>



-- 
Steven Gardner
All good men know the power of prayer...

**Comment by osh** [comment]
looks like this should be resolved on the latest version

**Comment by sgardner340** [comment]
I believe so Sorry for the late response I have had my hand full dealing
with Volk​'s gcc issues. As I stated before I agree this issue has been
resolved

On Wed, Sep 9, 2015 at 6:31 AM, osh <notifications@github.com> wrote:

> looks like this should be resolved on the latest version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osh/gr-eventstream/issues/9#issuecomment-138867752>.
>



-- 
Steven Gardner
All good men know the power of prayer...
